# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170810_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_types',
            field=models.CharField(choices=[('Knowledge', 'Knowledge'), ('Product', 'Product'), ('Question', 'Question')], default='Knowledge', max_length=10),
        ),
    ]
