# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
