# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170813_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
    ]
