# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170813_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
