# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170814_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 13, 17, 5, 38, 204964, tzinfo=utc)),
        ),
    ]
