# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20170814_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
